Plugin.Maui.ScreenSecurity/IScreenSecurity.cs, Plugin.Maui.ScreenSecurity/Platforms/Windows/ScreenSecurity.windows.cs, Plugin.Maui.ScreenSecurity/Plugin.Maui.ScreenSecurity.csproj, samples/ScreenSecuritySample/AppShell.xaml.cs, samples/ScreenSecuritySample/MauiProgram.cs, samples/ScreenSecuritySample/Platforms/Windows/App.xaml, samples/ScreenSecuritySample/Platforms/Windows/App.xaml.cs, samples/ScreenSecuritySample/Platforms/Windows/Package.appxmanifest, samples/ScreenSecuritySample/Platforms/Windows/app.manifest, samples/ScreenSecuritySample/ScreenSecuritySample.csproj, samples/ScreenSecuritySample/Views/MainPage.xaml, samples/ScreenSecuritySample/Views/MainPage.xaml.cs, samples/ScreenSecuritySample/Views/WindowsPages/ScreenshotProtectionPage.xaml, samples/ScreenSecuritySample/Views/WindowsPages/ScreenshotProtectionPage.xaml.cs
Added Windows support and sample.
=> Add Windows support

Plugin.Maui.ScreenSecurity/Platforms/Android/ScreenSecurity.android.cs
=> Bug/#06 Android thread exception

Plugin.Maui.ScreenSecurity/IScreenSecurity.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/ScreenSecurity.ios.cs, Plugin.Maui.ScreenSecurity/Plugin.Maui.ScreenSecurity.csproj, samples/ScreenSecuritySample/AppShell.xaml.cs, samples/ScreenSecuritySample/MauiProgram.cs, samples/ScreenSecuritySample/ScreenSecuritySample.csproj, samples/ScreenSecuritySample/Views/IOSPages/ScreenshotProtectionIOSPage.xaml, samples/ScreenSecuritySample/Views/IOSPages/ScreenshotProtectionIOSPage.xaml.cs, samples/ScreenSecuritySample/Views/MainPage.xaml, samples/ScreenSecuritySample/Views/MainPage.xaml.cs
=> Feature/#04 Add screenshot protection to iOS

Plugin.Maui.ScreenSecurity/Handlers/ErrorsHandler.cs, Plugin.Maui.ScreenSecurity/Platforms/Android/ScreenSecurity.android.cs, Plugin.Maui.ScreenSecurity/Platforms/Windows/NativeMethods.cs, Plugin.Maui.ScreenSecurity/Platforms/Windows/ScreenSecurity.windows.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Helpers/IOSWindowHelper.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Helpers/UIColorExtensions.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Protections/BlurProtectionManager.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Protections/ColorProtectionManager.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Protections/ImageProtectionManager.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Protections/ScreenRecordingProtectionManager.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Protections/ScreenshotProtectionManager.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/ScreenSecurity.ios.cs, samples/ScreenSecuritySample/AppShell.xaml.cs, samples/ScreenSecuritySample/MauiProgram.cs, samples/ScreenSecuritySample/Views/MainPage.xaml.cs
Improvements to increase code readability, performance and error handling.
=> Feature: Code improvements

Plugin.Maui.ScreenSecurity/IScreenSecurity.cs, Plugin.Maui.ScreenSecurity/Platforms/Android/ScreenSecurity.android.cs, Plugin.Maui.ScreenSecurity/Platforms/Windows/ScreenSecurity.windows.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Helpers/IOSHelpers.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Helpers/StringExtensions.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/ScreenSecurity.ios.cs, Plugin.Maui.ScreenSecurity/ScreenProtectionOptions.cs
Created and implemented a new set of unified APIs to be used cross-platform, without preprocessing directives.
=> Feature: Unify APIs

Plugin.Maui.ScreenSecurity/Platforms/iOS/Protections/BlurProtectionManager.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Protections/ImageProtectionManager.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Protections/ScreenshotProtectionManager.cs
=> Bug: iOS bugs

Plugin.Maui.ScreenSecurity/Platforms/Android/ScreenSecurity.android.cs, Plugin.Maui.ScreenSecurity/Platforms/Windows/NativeMethods.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Helpers/StringExtensions.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Protections/BlurProtectionManager.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Protections/ScreenshotProtectionManager.cs, Plugin.Maui.ScreenSecurity/Plugin.Maui.ScreenSecurity.csproj
Added .Net6 support to all platforms.
=> Feature: Add .Net6 support.

Plugin.Maui.ScreenSecurity/IScreenSecurity.cs, Plugin.Maui.ScreenSecurity/Platforms/Android/ScreenSecurity.android.cs, Plugin.Maui.ScreenSecurity/Platforms/Windows/ScreenSecurity.windows.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/ScreenSecurity.ios.cs
- Added blur as optional on iOS.
=> Feature: Make blur optional on iOS.

CHANGELOG.md, Plugin.Maui.ScreenSecurity/Plugin.Maui.ScreenSecurity.csproj, README.md
=> Version 1.1.5

Plugin.Maui.ScreenSecurity/Platforms/iOS/Helpers/IOSHelpers.cs
This should resolve #18 
Tested on two devices (iPhone SE 2023 and iPhone 14) updated to the latest iOS version. 
Might be turned into a one liner, but you get the gist of what's the solution.
Thanks for the great work with this plugin, would be nice if this could get published anytime soon as 1.1.6.
Best regards
=> iOS 17 fix

Plugin.Maui.ScreenSecurity/Platforms/Android/ScreenSecurity.android.cs, Plugin.Maui.ScreenSecurity/Platforms/Windows/NativeMethods.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Helpers/StringExtensions.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Protections/ScreenRecordingProtectionManager.cs, Plugin.Maui.ScreenSecurity/Plugin.Maui.ScreenSecurity.csproj, samples/ScreenSecuritySample/ScreenSecuritySample.csproj
=> Feature: Add .Net8 support

CHANGELOG.md, LICENSE, Plugin.Maui.ScreenSecurity/Plugin.Maui.ScreenSecurity.csproj, README.md
=> Version 1.1.6

Plugin.Maui.ScreenSecurity/Platforms/iOS/Helpers/IOSHelpers.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Protections/ScreenshotProtectionManager.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/ScreenSecurity.ios.cs
=> Bug: iOS 17 screenshot still not working

Plugin.Maui.ScreenSecurity/Platforms/Android/ScreenSecurity.android.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/ScreenSecurity.ios.cs
=> Added missed platform implementations of IsProtectionEnabled property.

Plugin.Maui.ScreenSecurity/Handlers/ScreenCaptureEventHandler.cs, Plugin.Maui.ScreenSecurity/IScreenSecurity.cs, Plugin.Maui.ScreenSecurity/MauiAppBuilderExtensions.cs, Plugin.Maui.ScreenSecurity/Platforms/Android/Helpers/AndroidHelpers.cs, Plugin.Maui.ScreenSecurity/Platforms/Android/ScreenSecurity.android.cs, Plugin.Maui.ScreenSecurity/Platforms/Windows/NativeMethods.cs, Plugin.Maui.ScreenSecurity/Platforms/Windows/ScreenSecurity.windows.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/ScreenSecurity.ios.cs, Plugin.Maui.ScreenSecurity/Plugin.Maui.ScreenSecurity.csproj, Plugin.Maui.ScreenSecurity/ScreenSecurity.net.cs, samples/ScreenSecuritySample/MauiProgram.cs, samples/ScreenSecuritySample/Platforms/Android/AndroidManifest.xml, samples/ScreenSecuritySample/ScreenSecuritySample.csproj, samples/ScreenSecuritySample/Views/SecondPage.xaml.cs
=> Feature: Add screen captured event

Plugin.Maui.ScreenSecurity/Platforms/iOS/ScreenSecurity.ios.cs, samples/ScreenSecuritySample/Views/SecondPage.xaml.cs
=> Added better iOS observer implementation for ScreenCaptured

CHANGELOG.md, Plugin.Maui.ScreenSecurity/Plugin.Maui.ScreenSecurity.csproj, README.md
=> New release 1.2.0

Plugin.Maui.ScreenSecurity/IScreenSecurity.cs, Plugin.Maui.ScreenSecurity/MauiAppBuilderExtensions.cs, Plugin.Maui.ScreenSecurity/Platforms/Android/Helpers/AndroidHelpers.cs, Plugin.Maui.ScreenSecurity/Platforms/Android/ScreenSecurity.android.cs, Plugin.Maui.ScreenSecurity/Platforms/Windows/ScreenSecurity.windows.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Helpers/IOSHelpers.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Protections/BlurProtectionManager.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Protections/ColorProtectionManager.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Protections/ImageProtectionManager.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Protections/ScreenRecordingProtectionManager.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/Protections/ScreenshotProtectionManager.cs, Plugin.Maui.ScreenSecurity/Platforms/iOS/ScreenSecurity.ios.cs, Plugin.Maui.ScreenSecurity/Plugin.Maui.ScreenSecurity.csproj, Plugin.Maui.ScreenSecurity/ScreenProtectionOptions.cs, Plugin.Maui.ScreenSecurity/ScreenSecurity.cs, samples/ScreenSecurityBlazorSample/Components/Pages/Home.razor, samples/ScreenSecurityBlazorSample/Platforms/Android/MainActivity.cs, samples/ScreenSecurityBlazorSample/Platforms/Android/MainApplication.cs, samples/ScreenSecurityBlazorSample/Platforms/iOS/AppDelegate.cs, samples/ScreenSecurityBlazorSample/Platforms/iOS/Info.plist, samples/ScreenSecurityBlazorSample/Platforms/iOS/Program.cs, samples/ScreenSecurityBlazorSample/ScreenSecurityBlazorSample.csproj, samples/ScreenSecuritySample/Platforms/Android/AndroidManifest.xml, samples/ScreenSecuritySample/Platforms/Android/MainActivity.cs, samples/ScreenSecuritySample/Platforms/Android/MainApplication.cs, samples/ScreenSecuritySample/Platforms/iOS/AppDelegate.cs, samples/ScreenSecuritySample/Platforms/iOS/Info.plist, samples/ScreenSecuritySample/Platforms/iOS/Program.cs, samples/ScreenSecuritySample/ScreenSecuritySample.csproj, samples/ScreenSecuritySample/Views/MainPage.xaml.cs
=> Feature: Add .Net9 support

CHANGELOG.md, LICENSE, Plugin.Maui.ScreenSecurity/Plugin.Maui.ScreenSecurity.csproj, README.md
=> New release 1.2.1

samples/ScreenSecurityBlazorSample/ScreenSecurityBlazorSample.csproj, samples/ScreenSecuritySample/ScreenSecuritySample.csproj
=> Bug: Sample projects don't compile.
